--Para remotemysql
use pg5dcP32qz;
--use VinoappDB;

insert into usuarios (usuario_id, cuenta_usuario, nombre, apellido, pais, region, ciudad, email, cod_postal)
values (null,'vinoadicto', 'Juan', 'Perez', 'Argentina', 'Corrientes', 'Corrientes', 'jperez@gmail.com', '1551'),
(null,'gbianco', 'Gabriel', 'Bianco', 'Argentina', 'Buenos Aires', 'CABA', 'gabianco@hotmail.com','1414'),
(null,'madarreta','Marcelo','Idarreta','España','País Vasco', 'San Sebastian', 'mgidarreta@ibernet.es', '1234'),
(null,'ellucho', 'Luis', 'Logroño', 'España', 'Madrid', 'Madrid', 'llogronov@vodafone.es', '1523'),
(null,'lolag','Luisa','Gonzalez','Chile','Santiago','Santiago','lolachichi@hotmail.com','101010'),
(null,'avidal','Arturo','Vidal','Chile','Santiago','Santiago','avidal@gmail.com','1313'),
(null,'leoleo','Leonardo','Larrazábal','Venezuela','DC','Caracas','leonesxsiempre@hotmail.com','1010'),
(null,'tomcat12','Luis','Angarita','Venezuela','Guarico','Calabozo','luislll@gmail.com','1515'),
(null,'coco10mil','Carlos','Lopez','Colombia','Antioquia','Medellin','carlopez@telcom.co','009999'),
(null,'lanatabella','Maria','Lanata','Colombia','Santander','Bucaramanga','lala1232@gmail.com','9991200'),
(null,'lartaud','Louis','Artaud','Francia','Isla de Francia','Paris','lcartaud@fnet.fr','56656'),
(null,'lablanc','Laurent','Blanc','Francia','Isla de Francia','Paris','blancno4@fnet.fr','33232'),
(null,'mattwein','Matthias','Sammer','Alemania','Baviera','Munich','mattsam@web.de','12134'),
(null,'arnelau','Arne','Lau','Alemania','Baden-Wurtemberg','Stuttgart','laulau@tmobil.de','76776'),
(null,'tomalcant','Tomas','Alcántara','Ecuador','Pichincha','Quito','tomasalcantaraa@gmail.com','1111'),
(null,'linalabella','Lina','Linares','Ecuador','Guayas','Guayaquil','linalabella27@gmail.com','9897'),
(null,'pintocaritas','Juan','Pinto','Bolivia','La Paz','La Paz','pintoj@hotmail.com','1315'),
(null,'quechuavino','Evo','Gonzalez','Bolivia','La Paz','La Paz','evogol@hotmail.com','1212'),
(null,'locosporelvino','Cornelio','Lorenzo','Argentina','Mendoza','Mendoza','corneliovino@fibertel.com.ar','1019'),
(null,'antonperez','Anton','Perez','Argentina','San Juan','San Juan','antonp95@fiberel.com.ar','1210'),
(null,'lolopololo','Juan','Quiñones','Argentina','Mendoza','Maipu','jquino@fibertel.com.ar','12120'),
(null,'amoelvino','Liliana','Martinez','Argentina','Salta','Salta','lilimartin@hotmail.com','1919'),
(null,'luisgomez','Luis','Gomez','Chile','Valdivia','Valdivia','lgomez@gmail.com','44040'),
(null,'charanguis','Charles','Aranguis','Chile','Santiago','Santiago','caranguis@fibertel.com.ch','9900'),
(null,'luchosuarez','Luis','Suarez','Uruguay','Montevideo','Montevideo','lsuarez@barcelonafc.es','2345'),
(null,'davidd','David','Duarte','Uruguay','Maldonado','Punta del Este','davidduarte69@gmail.com','2828'),
(null,'jjna990','Juan Jose','Nandez','Uruguay','Colonia','Colonia','jjnandez@hotmail.com','1468'),
(null,'jjohnson','John','Johnson','Estados Unidos','California','Los Angeles','jcjohnson23@at&t.us','9090909'),
(null,'edwines','Edward','Cobblestone','Estados Unidos','California','San José','edcobb@at&t.us','9178433'),
(null,'amandaloveswines','Amanda','Watson','Estados Unidos','New York','New York','amandawatson@fibernet.us','555252'),
(null,'jperezz','Juan Diego','Perez','Filipinas','Isla de Luzón','Ciudad Quezón','jdperez@fillipinestech.ph','0092'),
(null,'mateovino99','Mateo','Rodriguez','Filipinas','Isla de Luzón','Manila','mateorod@gmail.com','09899'),
(null,'jalbert','Juan Alberto','Rivadenera','España','Pontevedra','Vigo','jrivadenera0623@ibernet.es','101012'),
(null,'tostonloco','Juan Carlos','Ramirez','Venezuela','Monagas','Maturin','jcram245@hotmail.com','9898'),
(null,'fnunez','Francisco','Nuñez','Colombia','Santander','Popayán','fnunez@gmail.com','1010124'),
(null,'lomatt','Lothar','Mattheus','Alemania','Berlin','Berlin','lothartor@web.de','77673'),
(null,'nolsen1212','Niklas','Olsen','Alemania','Brandenburgo','Postdam','nolsen@gmail.com','029832'),
(null,'ozhabot','Oleg','Zhabotny','Rusia','Moscu','Moscu','obzhavot22@net.ru','775473'),
(null,'natil90','Natalia','Luongo','Argentina','Neuquen','Neuquen','natalial99@fibertel.com.ar','1991');
select * from usuarios;

insert into bodegas (bodega_id, nombre_bodega, pais, ubicacion, fundacion)
values (null,'Trapiche','Argentina','Mendoza',1883),
(null,'Pomar','Venezuela','Barquisimeto',1985),
(null,'Salentein','Argentina','Mendoza',1996),
(null,'Zuccardi','Argentina','Mendoza',1963),
(null,'Catena Zapata','Argentina','Mendoza',1902),
(null,'Garzon','Uruguay','Maldonado',1999),
(null,'Septima','Argentina','Mendoza',2001),
(null,'Chakana Wines','Argentina','Mendoza',2002),
(null,'El Esteco','Argentina','Salta',1994),
(null,'Andeluna','Argentina','Mendoza',2003),
(null,'Marques de Caceres','España','La Rioja',1970),
(null,'Trivento','Argentina','Mendoza',1996),
(null,'Chateau de Sales','Francia','Pomerol',1602),
(null,'Ferreira','Portugal','Porto',1751),
(null,'Les Vins Georges Duboeuf','Francia','Beaujolais',1964),
(null,'Durigutti','Argentina','Mendoza',2002),
(null,'Patritti','Argentina','Neuquen',2003),
(null,'Montes Wines','Chile','Colchagua',1987),
(null,'Piatelli','Argentina','Mendoza',2002),
(null,'Concha y Toro','Chile','Pirque',1883),
(null,'Bodega del Sol','Argentina','Mendoza',2008),
(null,'Protos','España','Ribera del Duero', 1927),
(null,'Vina Tarapaca','Chile','Isla de Maipo',1874);
select * from bodegas;

insert into tiendas (tienda_id, nombre_T, pais, ciudad, direccion, pagina_web)
values (null,'Baltimore','Argentina','CABA','Av. Alvarez Thomas 299','https://www.tiendabaltimore.com/'),
(null,'Licores Mundiales','Venezuela','Caracas','Av. Rio de Janeiro','https://www.licoresmundiales.com/'),
(null,'Sobran los motivos','Argentina','CABA','Villa Crespo','https://www.sobranlosmotivos.com.ar/'),
(null,'Musa Vinos de Autor','Argentina','Bahia Blanca','Florida 1321','https://es-la.facebook.com/musavinosdeautor/'),
(null,'Deviche','Argentina','Buenos Aires','CABA','http://www.deviche.com.ar/'),
(null,'20 Vinos Distribuidora','Argentina','CABA','Caballito','https://www.instagram.com/20vinosdistribuidora/'),
(null,'Espacio Vino','Argentina','CABA','Santo Tome 3852','https://www.espaciovino.com.ar/'),
(null,'On The Rocks Ar','Argentina','CABA','Rosario 839','https://www.ontherocksar.com.ar/'),
(null,'La Proveduria Club de Vinos','Argentina','CABA','Malabia 11','http://laproveeduriaclubdevinos.com.ar/#!/-home/'),
(null,'Grand Cru Argentina','Argentina','CABA','Rodriguez Peña 1886','http://www.grandcru.com.ar/'),
(null,'Señor Gonzalez','Argentina','CABA','Carlos Calvo 4289','https://senor-gonzalez-wine-store.negocio.site/'),
(null,'Malambo','Argentina','CABA','Thames 2098','https://www.instagram.com/malambovinoteca/'),
(null,'Frappe','Argentina','CABA','Gral. Lucio Norberto Mansilla 3402','https://frappe.com.ar/'),
(null,'Bodega Amparo','Argentina','CABA','Darwin 1548','http://www.bodegaamparo.com.ar/'),
(null,'Ligier Vinotecas','Argentina','CABA','Av. Rivadavia 4995','https://vinotecaligier.com/'),
(null,'Ozono Drinks','Argentina','CABA','La Rioja 1823','http://www.ozonodrinks.com.ar/'),
(null,'Vinoteca Bari','Argentina','CABA','Martin Rodriguez 532','https://bari.com.ar/'),
(null,'Monaco Vinos Particulares','Argentina','CABA','Bolivar 1556','https://www.vinosparticulares.com/'),
(null,'Der Weinladen','Alemania','Nagold','Markstrasse 47','https://weinladennagold.de/'),
(null,'Findorffer Weinladen','Alemania','Bremen','Hemmstrasse 179','https://www.findorffer-weinladen.de/'),
(null,'Weinladen Lemberger','Alemania','Baviera','Ludwig-Hermann-Strasse 1','https://www.weinladen-lemberger.de/'),
(null,'La Tintoreria Vinoteca','España','Madrid','Calle Gurtubay 4','https://latintoreriavinoteca.com/'),
(null,'La Vinoteca','España','Madrid','Calle del Principe 27','https://www.vinoteca-barbechera.com/'),
(null,'Vinoteca Tierra','España','Madrid','Calle de Ayala 28','https://www.vinotecatierra.es/main/'),
(null,'Entrevinos','España','Madrid','Calle de Ferraz 26','http://www.entrevinos.net/'),
(null,'Lavinia','España','Madrid','Calle de Jose Ortega y Gasset 16','https://www.lavinia.es/es'),
(null,'Vides','España','Madrid','Calle de la Libertad 12','https://vinotecavides.es/es/home/'),
(null,'Vinos Baco','España','Madrid','Calle de San Bernardo 117','https://www.vinosbaco.com/'),
(null,'Maracuya Vinoteca','España','Madrid','Plaza de la Cebada 33-34','https://eltastevin.wordpress.com/'),
(null,'Hay Pan','Bolivia','La Paz','Murillo 764','https://www.instagram.com/hay_pan_/'),
(null,'Hallwrights','Bolivia','La Paz','Sanchez Lima 2235',null),
(null,'Cepas Mendocinas','Bolivia','La Paz','Almirante Grau 483','http://www.cepasmendocinas.com/'),
(null,'Wine Lovers','Colombia','Bogota','Calle 127','https://clubwinelovers.com/'),
(null,'Cava Wine Bar & Shop','Colombia','Bogota','Carrera 6 #67-63','https://www.cava.com.co/'),
(null,'Beacon Wine and Spirits','Estados Unidos','New York','2120 Broadway','http://www.beaconwine.com/'),
(null,'Sherry-Lehmann','Estados Unidos','New York','505 Park Avenue','https://www.sherry-lehmann.com/'),
(null,'The Wine Store','Colombia','Bogota','Calle 81','http://www.thewinestore.com.co/');
select * from tiendas;

insert into vinos (vino_id, nombre, cepas, color, cosecha, categoria, enologo, bodega_id, terruno)
values (null,'Protos crianza','Tempranillo','tinto',2016,'reserva',null,21,'Ribera del Duero'),
(null,'Protos Gran Reserva','Tempranillo','tinto',2012,'gran_reserva',null,21,'Ribera del Duero'),
(null,'Trinita','Malbec,Cab.Sauvignon,Merlot','tinto',2015,'gran_reserva',null,19,'Lujan de Cuyo'),
(null,'Grand Reserve','Malbec','tinto',2014,'gran_reserva',null,19,'Lujan de Cuyo'),
(null,'Grand Reserve','Cabernet Sauvignon','tinto',2012,'gran_reserva',null,19,'Lujan de Cuyo'),
(null,'Reserve','Malbec','tinto',2016,'gran_reserva',null,19,'Lujan de Cuyo'),
(null,'Malamado','Malbec','tinto',2019,'licoroso',null,4,'Valle de Uco'),
(null,'Soleria','Torrontes','blanco',2019,'licoroso',null,4,'Maipu-Santa Rosa'),
(null,'Animado','Torrontes','blanco',2019,'licoroso',null,4,'Maipu'),
(null,'Zuccardi Aluvional','Malbec','tinto',2013,'gran_reserva','Sebastian Zuccardi',4,'Gualtallary'),
(null,'Zuccardi Aluvional','Malbec','tinto',2011,'gran_reserva','Sebastian Zuccardi',4,'Paraje Altamira'),
(null,'Zuccardi Concreto','Malbec','tinto',2014,'reserva','Sebastian Zuccardi',4,'Paraje Altamira'),
(null,'Zuccardi Q','Chardonnay','blanco',2010,'gran_reserva','Ruben Ruffo',4,'Tupungato'),
(null,'Brazos de los Andes','Malbec,Cab.Sauvignon,Syrah,Bonarda','tinto',2013,'gran_reserva','Sebastian Zuccardi',4,'Valle de Uco'),
(null,'Zuccardi Blanc des Blancs','Chardonnay','blanco',2008,'espumante_brut','Sebastian Zuccardi',4,'Tupungato'),
(null,'Santa Julia Tardío','Torrontes, Viogner','blanco',2018,'late_harvest','Ruben Ruffo',4,'Maipu-Santa Rosa'),
(null,'Santa Julia Magna Corte','Cab.Sauvignon,Malbec,Syrah','tinto',2016,'reserva','Ruben Ruffo',4,'Valle de Uco'),
(null,'Pomar Reserva','Petit Verdot,Syrah,Tempranillo','tinto',2014,'gran_reserva',null,2,'Lara'),
(null,'Pomar Demi Sec','Chenin Blanc,Macabeu,Malvoisie','blanco',2016,'espumante_demisec',null,2,'Lara'),
(null,'Iscay','Malbec, Cabernet Franc','tinto',2011,'gran_reserva',null,1,'Cruz de Piedra, Maipu, Altamira'),
(null,'Trapiche Terroir Series','Cabernet Sauvignon','tinto',2012,'gran_reserva',null,1,'Valle de Uco'),
(null,'Trapiche Terroir Series','Malbec','tinto',2014,'gran_reserva',null,1,'Valle de Uco'),
(null,'Trapiche Costa y Pampa','Pinot Noir','tinto',2014,'gran_reserva',null,1,'Chapadmalal'),
(null,'Trapiche Costa y Pampa','Chardonnay','rosado',2016,'espumante_brut',null,1,'Chapadmalal'),
(null,'Trapiche Costa y Pampa','Sauvignon Blanc','blanco',2014,'gran_reserva',null,1,'Chapadmalal'),
(null,'Trapiche Gran Medalla','Cabernet Franc','tinto',2014,'gran_reserva',null,1,'Valle de Uco'),
(null,'Trapiche Gran Medalla','Chardonnay','blanco',2015,'gran_reserva',null,1,'Valle de Uco'),
(null,'Fond de Cave Gran Reserva','Cabernet Sauvignon','tinto',2013,'gran_reserva',null,1,'Maipu'),
(null,'Fond de Cave Gran Reserva','Malbec','tinto',2013,'gran_reserva',null,1,'Valle de Uco'),
(null,'Septima 10 Barricas GR','Tannat','tinto',2011,'gran_reserva','Paula Borgo',7,'Lujan de Cuyo'),
(null,'Septima 10 Barricas GR','Cabernet Franc','tinto',2016,'gran_reserva','Paula Borgo',7,'Tunuyan'),
(null,'Septima Lote Especial','Malbec','tinto',2014,'gran_reserva','Paula Borgo',7,'Lujan de Cuyo'),
(null,'Confiado','Malbec','tinto',2017,'reserva','Paula Borgo',7,'Altamira'),
(null,'Septima Obra','Pinot Noir','tinto',2018,'joven','Paula Borgo',7,'Los Chacayes, Altamira'),
(null,'Mundus Bacillus Terrae','Malbec','tinto',2008,'gran_reserva',null,5,'Gualtallary'),
(null,'Mundus Bacillus Terrae','Malbec','tinto',2014,'gran_reserva',null,5,'Gualtallary'),
(null,'Catena Alta','Malbec','tinto',2008,'gran_reserva',null,5,'Gualtallary'),
(null,'Catena Appellation','Malbec','tinto',2015,'gran_reserva',null,5,'Vista Flores'),
(null,'Adrianna Vineyards White Bones','Chardonnay','blanco',2017,'reserva','Alejandro Vigil',5,'Gualtallary'),
(null,'Catena Zapata Nicasia Vineyards','Malbec','tinto',2016,'reserva',null,5,'Altamira'),
(null,'DV Catena Tinto Historico','Malbec','tinto',2015,'gran_reserva',null,5,'Lulunta,Gualtallary,El Cepillo'),
(null,'Adrianna Vineyards River Stones','Malbec','tinto',2014,'gran_reserva','Alejandro Vigil',5,'Gualtallary'),
(null,'Balasto','Tannat,C.Franc,Merlot,Marselan','tinto',2017,'reserva','German Bruzzone',6,'Garzon'),
(null,'Garzon','Albarino','blanco',2019,'reserva','German Bruzzone',6,'Garzon'),
(null,'Garzon','Marselan','tinto',2019,'reserva','German Bruzzone',6,'Garzon'),
(null,'Garzon','Pinot Noir','rosado',2018,'reserva','German Bruzzone',6,'Garzon'),
(null,'SIMOF','Tempranillo','tinto',2019,'reserva','Fernando Costa',11,'Rioja Alta, Rioja Alavesa'),
(null,'Gaudium','Tempranillo,Graciano','tinto',2014,'gran_reserva','Fernando Costa',11,'Rioja Alta, Rioja Alavesa'),
(null,'Excellens','Garnacha,Tempranillo','rosado',2018,'joven','Fernando Costa',11,'Rioja Alta,Cenicero,Rioja Alavesa'),
(null,'Don Melchor','Cabernet Sauvignon,Cabernet Franc','tinto',2017,'gran_reserva','Enrique Tirado',20,'Valle del Alto Maipo'),
(null,'Terrunyo','Cabernet Sauvignon','tinto',2016,'reserva','Ignacio Recabarren',20,'Pirque'),
(null,'Gravas Blancas','Sauvignon Blanc','blanco',2016,'reserva','Enrique Tirado',20,'Valle el Bio-Bio'),
(null,'Tarapaca Gran Reserva','Cabernet Sauvignon','tinto',2018,'gran_reserva','Sebastian Ruiz',22,'Valle del Maipo'),
(null,'Tarapaca Etiqueta Negra','Cabernet Sauvignon','tinto',2017,'gran_reserva','Sebastian Ruiz',22,'Valle del Maipo'),
(null,'Tarapaca Late Harvest','Gewurztraminer,S.Blanc,Moscatel','blanco',2012,'late_harvest','Sebastian Ruiz',22,'Valle Central');
select * from vinos;

insert into premios (premio_id, nombre_premio, puntaje, medalla,ano,vino_id)
values (null,'Wine Enthusiast',91,null,2015,113),
(null,'Wine Spectator',91,null,2014,114),
(null,'Robert Parker Wine Advocate',91,null,2012,115),
(null,'jamessuckling.com',92,null,2016,116),
(null,'Vinus',96,'oro',2019,117),
(null,'Vinus',94,'oro',2019,119),
(null,'Vinus',93,'oro',2019,118),
(null,'Wine and Spirits Competition',92,'plata',2019,118),
(null,'Tim Atkin',96,null,2011,120),
(null,'Robert Parker Wine Advocate',92,null,2012,112),
(null,'Robert Parker Wine Advocate',98,null,2014,142),
(null,'Vinalies',null,'plata',2014,122),
(null,'Tim Atkin',98,null,2017,149);
select * from premios;

insert into rankings(ranking_id, ranking, usuario_id, vino_id,tienda_id)
values (null,'r4',1,131,1),
(null,'r5',1,137,1),
(null,'r3',1,120,1),
(null,'r5',1,112,2),
(null,'r4',1,114,4),
(null,'r5',1,115,9),
(null,'r4',1,118,10),
(null,'r4',1,143,37),
(null,'r3',1,147,29),
(null,'r4',2,155,33),
(null,'r4',5,154,31),
(null,'r5',5,150,36),
(null,'r4',39,111,36),
(null,'r3',39,119,17),
(null,'r2',31,118,20),
(null,'r4',30,112,20),
(null,'r4',30,145,22),
(null,'r3',30,149,25),
(null,'r5',34,149,7),
(null,'r5',34,149,7),
(null,'r3',36,150,8),
(null,'r3',37,130,9),
(null,'r4',23,130,13),
(null,'r4',21,131,16),
(null,'r5',20,125,35),
(null,'r5',20,122,34),
(null,'r5',12,121,35),
(null,'r4',12,123,29),
(null,'r4',19,116,27),
(null,'r3',18,118,4),
(null,'r1',27,139,9),
(null,'r5',27,139,9),
(null,'r5',27,139,9),
(null,'r4',27,139,9),
(null,'r3',27,139,9),
(null,'r5',27,111,21);
select * from rankings;

insert into bodegapremios (nombre_premiobod, distincion, ano, bodega_id)
values("Great Wine Capitals-Best of Wine Tourism", "oro", 2018, 1),
("Trip Advisor", "Certificado de Excelencia", 2018, 1),
("Civic Trust Award", null, 2010, 22);

